export const TRANSITION_UPDATE_SUBSCRIPTION = 'TRANSITION_UPDATE_SUBSCRIPTION';
export const TRANSITION_CANCEL_SUBSCRIPTION = 'TRANSITION_CANCEL_SUBSCRIPTION';
export const TRANSITION_RESTART_SUBSCRIPTION = 'TRANSITION_RESTART_SUBSCRIPTION';