export const PAGE_LISTING_TYPE = 'PAGE_LISTING';
export const PRODUCT_LISTING_TYPE = 'PRODUCT_LISTING';
export const SUPPORTED_LISTING_TYPE = [
  PAGE_LISTING_TYPE,
  PRODUCT_LISTING_TYPE
];
export const LISTING_STATE_DRAFT = 'draft';
export const LISTING_STATE_PENDING_APPROVAL = 'pendingApproval';
export const LISTING_STATE_PUBLISHED = 'published';
export const LISTING_STATE_CLOSED = 'closed';
export const TEAM_MEMBER_ADD = 'TEAM_MEMBER_ADD';
export const TEAM_MEMBER_REMOVE = 'TEAM_MEMBER_REMOVE';
export const TEAM_MEMBER_RESEND = 'TEAM_MEMBER_RESEND';
export const TEAM_MEMBER_CREATION = 'TEAM_MEMBER_CREATION';
export const COMPANY_CREATION = 'COMPANY_CREATION';
export const COMPANY_CHANGE_PLAN = 'COMPANY_CHANGE_PLAN';